name: Release
on:
    push:
        branches: 'main'

jobs:
    compute:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: pip install -r requirements.txt
            - run: python3 compute.py
            - run: echo "CURRENT_DATE=$(date +%F)" >> "$GITHUB_ENV"
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: false
                title: "MK8 Scores - $CURRENT_DATE"
                files: |
                    results/*
            